### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by ftalbrecht**
Mhm, was this never executed then, @renefritze?

### CODE REVIEW

**Comment by renefritze** [comment]
Yeah, if you look into `.ci/gitlab-ci.yml` there's a step for it, but execution is disabled. I'll hijack this PR to see if your fix actually fixes the whole test too. 

Sidenote: `automerge` does nothing here. Github has had builtin auto-merge for a while. 
Sidenote 2: You actually typo'ed the typo fix commit message :stuck_out_tongue_winking_eye:

**Comment by renefritze** [comment]
The CI job succeeds now, but really, [it should](https://zivgitlab.uni-muenster.de/pymor/docker/-/jobs/996941#L575) still fail.

**Comment by ftalbrecht** [comment]
> 

Now it fails, nice!

**Comment by ftalbrecht** [comment]
On 10.06.22 17:45, René Fritze wrote:
> There's actually some weird stuff happening in the import check that I will need to look at in depth at some point. I'll keep this open until then, if you don't mind @ftalbrecht

Not at all, its all yours! :)

**Pull request closed without merging**
